meta_product_name: "Woolks"
meta_title: "Wooks - Tailored walks for your companion anywhere in the world !"
meta_description: "Find great walks for you and your best friends"
meta_image: "surfdog.jpg" # should exist in `app/assets/images/`
